package com.show_music;

public final class UnlockHints {
	private UnlockHints() { throw new UnsupportedOperationException("no instances"); }

	public static String getUnlockHint(String nowPlaying) {
        switch(nowPlaying) {
			case "7th Realm": return "Unlocked in the Brimhaven Dungeon";
			case "Adventure": return "Unlocked in Varrock";
			case "Al Kharid": return "Unlocked in Al Kharid";
			case "Alchemical Attack!": return "Unlocked inside the Alchemical Hydra lair";
			case "All's Fairy in Love & War": return "Unlocked at the Fairy Resistance Hideout during the Fairytale II - Cure a Queen quest";
			case "Alone": return "Unlocked in the Clock Tower Dungeon and Ice Mountain";
			case "Altar Ego": return "Unlocked in the Ourania Cave";
			case "Alternative Root": return "Unlocked in the Tunnel of Chaos after completion of What Lies Below";
			case "Amascut's Promise": return "Unlocked during the battle with the Wardens in the Tombs of Amascut";
			case "Ambient Jungle": return "Unlocked at Shilo Village";
			case "The Ancient Prison": return "Unlocked in the Ancient Prison";
			case "The Angel's Fury": return "Unlocked during the fight with Nex";
			case "Anywhere": return "Unlocked at Marim's main gate";
			case "Ape-ex Predator": return "Unlocked during the battle with the Ba-Ba in the Tombs of Amascut";
			case "Arabian": return "Unlocked in Al Kharid";
			case "Arabian 2": return "Unlocked in Al Kharid";
			case "Arabian 3": return "Unlocked outside of the Kalphite Lair";
			case "Arabique": return "Unlocked in the hellhound area of Taverley Dungeon";
			case "Arachnids of Vampyrium": return "Unlocked during the fight in the Nylocas' nest in the Theatre of Blood";
			case "Arboretum": return "Unlocked during the Sins of the Father quest";
			case "Arcane": return "Unlocked in Arceuus";
			case "Architects of Prifddinas": return "Unlocked upon entering Prifddinas";
			case "Are You Not Entertained?": return "Unlocked in the Fortis Colosseum.";
			case "Armadyl Alliance": return "Unlocked in the God Wars Dungeon";
			case "Armageddon": return "Unlocked in the God Wars Dungeon";
			case "Army of Darkness": return "Unlocked in the Wilderness";
			case "Arrival": return "Unlocked in Falador";
			case "Artistry": return "Unlocked during the Mime Random Event";
			case "Ascent": return "Unlocked at Mount Quidamortem";
			case "Assault and Battery": return "Unlocked during the Barbarian Assault minigame";
			case "Attack 1": return "Unlocked in the Khazard Battlefield";
			case "Attack 2": return "Unlocked in Elvarg's lair during the Dragon Slayer I quest";
			case "Attack 3": return "Unlocked in the Lava Maze dungeon";
			case "Attack 4": return "Unlocked during the Fight Arena quest";
			case "Attack 5": return "Unlocked in the King Black Dragon cave";
			case "Attack 6": return "Unlocked at the Gu'Tanoth Ogre Enclave";
			case "Attention": return "Unlocked in Rimmington";
			case "Autumn Voyage": return "Unlocked in Lumbridge";
			case "Awful Anthem": return "Unlocked during Throne of Miscellania";
			case "Aye Car Rum Ba": return "Unlocked on Braindeath Island";
			case "Aztec": return "Unlocked at the Brimhaven Agility Arena";
			case "Back to Life": return "Unlocked in Sophanem. After the Contact! quest, it replaces the City of the Dead music track.";
			case "Background": return "Unlocked on Entrana";
			case "Bait": return "Unlocked during A Taste of Hope";
			case "Ballad of Enchantment": return "Unlocked at the Ardougne Monastery";
			case "Ballad of the Basilisk": return "Unlocked during The Fremennik Exiles";
			case "Bandit Camp": return "Unlocked at the Bandit Camp in the Kharidian Desert";
			case "Bandos Battalion": return "Unlocked in the God Wars Dungeon";
			case "Bane": return "Unlocked in the Corporeal Beast boss room";
			case "The Bane of Ashihama": return "Unlocked during the fight with The Nightmare";
			case "Barb Wire": return "Unlocked north of Baxtorian Falls, in the Ancient Cavern";
			case "Barbarian Workout": return "Unlocked during the Below Ice Mountain quest";
			case "Barbarianism": return "Unlocked at Barbarian Village";
			case "Barking Mad": return "Unlocked at the Werewolf Agility Course";
			case "Baroque": return "Unlocked at the Ardougne Market";
			case "Barren Land": return "Unlocked during the Making Friends with My Arm quest";
			case "Beetle Juice": return "Unlocked during the Contact! quest";
			case "Beneath Cursed Sands": return "Unlocked in Nexus within the Tombs of Amascut";
			case "Beneath the Kingdom": return "Unlocked in the Catacombs of Kourend";
			case "Beneath the Stronghold": return "Unlocked in the Gnome Stronghold Slayer Cave";
			case "Beyond": return "Unlocked in the Dwarven Tunnel under White Wolf Mountain";
			case "Beyond the Meadow": return "Unlocked west of Hosidius";
			case "Big Chords": return "Unlocked near the west entrance to Yanille";
			case "Black of Knight": return "Unlocked upon entering the Black Knight Catacombs during the While Guthix Sleeps quest";
			case "Blistering Barnacles": return "Unlocked on the Braindeath Island Mountain";
			case "Blood Rush": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Bloodbath": return "Unlocked at Slepe";
			case "Bob's on Holiday": return "Unlocked during A Tail of Two Cats";
			case "Body Parts": return "Unlocked in the Experiment cave south-east of Fenkenstrain's Castle";
			case "Bolrie's Diary": return "Unlocked during The Path of Glouphrie";
			case "Bone Dance": return "Unlocked west of Mort'ton";
			case "Bone Dry": return "Unlocked in the Smoke Dungeon near Pollnivneach";
			case "Book of Spells": return "Unlocked in Lumbridge";
			case "Borderland": return "Unlocked east of Rellekka";
			case "Box of Delights": return "Unlocked in the Mimic Chest";
			case "Brain Battle": return "Unlocked during The Great Brain Robbery";
			case "Breeze": return "Unlocked at Isafdar near the Underground Pass";
			case "Brew Hoo Hoo!": return "Unlocked in the Port Phasmatys brewery basement";
			case "Brimstail's Scales": return "Unlocked at Brimstail's cave";
			case "Bubble and Squeak": return "Unlocked at the Keldagrim Rat Pits";
			case "Bunny's Sugar Rush": return "Unlocked during the 2015 Easter Event";
			case "Burning Desire": return "Unlocked on Mount Karuulm";
			case "The Burning Sun": return "Unlocked during the Children of the Sun quest";
			case "Cabin Fever": return "Unlocked during the Cabin Fever quest";
			case "Cain's Tutorial": return "Unlocked during the Barbarian Assault tutorial";
			case "Call of the Tlati": return "Unlocked in the Tlati Rainforest";
			case "Camelot": return "Unlocked at Camelot";
			case "Castle Wars": return "Unlocked while playing the Castle Wars minigame";
			case "Catacombs and Tombs": return "Unlocked during Land of the Goblins";
			case "Catch Me If You Can": return "Unlocked at the Ardougne Rat Pits";
			case "Cave Background": return "Unlocked at the Dwarven Mine";
			case "Cave of Beasts": return "Unlocked during the Mountain Daughter quest";
			case "Cave of the Goblins": return "Unlocked in the Lumbridge Swamp Caves";
			case "Cavern": return "Unlocked at Yanille Agility dungeon";
			case "The Cellar Dwellers": return "Unlocked at the Ardougne Sewers during the Hazeel Cult quest";
			case "Cellar Song": return "Unlocked at the vault under the Varrock West Bank";
			case "Chain of Command": return "Unlocked during the Temple of Ikov quest";
			case "Chamber": return "Unlocked on the middle floor of the Haunted Mine";
			case "Chef Surprise": return "Unlocked in the Lumbridge Castle Dining Hall during the Recipe for Disaster quest";
			case "Chickened Out": return "Unlocked in the Evil Chicken's Lair during the Recipe for Disaster quest";
			case "Children of the Sun": return "Unlocked during the Children of the Sun quest";
			case "Chompy Hunt": return "Unlocked east of Feldip Hills near Rantz";
			case "The Chosen": return "Unlocked during the Recruitment Drive quest";
			case "City of the Dead": return "Unlocked in Sophanem. After the Contact! quest, it is replaced by the Back to Life music track.";
			case "The City of Sun": return "Unlocked in Civitas illa Fortis.";
			case "Clan Wars": return "Unlocked in a Clan Wars arena. (Random between this song and Warpath, re-enter to unlock both)";
			case "Clanliness": return "Unlocked in a Clan Hall";
			case "Claustrophobia": return "Unlocked in the gold mine from Between a Rock...";
			case "Close Quarters": return "Unlocked in the Wilderness";
			case "Coil": return "Unlocked during the fight with Zulrah (Can be unlocked while spectating using fairy ring code DLR)";
			case "Colossus of the Deep": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Competition": return "Unlocked in the Burthorpe Games Room";
			case "Complication": return "Unlocked at the Chaos Altar";
			case "Confrontation": return "Unlocked during the A Kingdom Divided quest";
			case "The Consortium": return "Unlocked during The Giant Dwarf";
			case "Conspiracy": return "Unlocked during A Taste of Hope";
			case "Contest": return "Unlocked while fighting Dad during Troll Stronghold";
			case "Corporal Punishment": return "Unlocked in the Drill Demon random event";
			case "Corridors of Power": return "Unlocked in the Subterranean Village during Royal Trouble";
			case "Country Jig": return "Unlocked in Hosidius";
			case "Courage": return "Unlocked in the blue dragon section of Taverley Dungeon";
			case "Creature Cruelty": return "Unlocked during the Tower of Life quest";
			case "Creatures of Varlamore": return "Unlocked in the Avium Savannah";
			case "Creeping Vines": return "Unlocked in the Hespori cave in the Farming Guild";
			case "Crest of a Wave": return "Unlocked automatically";
			case "Crystal Castle": return "Unlocked south-east of Prifddinas";
			case "Crystal Cave": return "Unlocked at Zanaris market";
			case "Crystal Sword": return "Unlocked in the Wilderness";
			case "Cursed": return "Unlocked in the Underground Pass, also plays in the Wrath Altar in the Myths' Guild";
			case "The Curtain Closes": return "Unlocked upon the defeat of Verzik Vitur";
			case "Dagannoth Dawn": return "Unlocked in Waterbirth Island";
			case "Dance of Death": return "Unlocked on the lowest floor of the Stronghold of Security";
			case "Dance of the Meilyr": return "Unlocked upon entering Prifddinas";
			case "Dance of the Nylocas": return "Unlocked in the Nylocas' nest in the Theatre of Blood";
			case "Dance of the Undead": return "Unlocked at the Barrows";
			case "Dangerous": return "Unlocked in the Wilderness";
			case "A Dangerous Game": return "Unlocked upon entering the Wilderness Slayer Cave";
			case "Dangerous Logic": return "Unlocked in Movario's base during the While Guthix Sleeps quest";
			case "Dangerous Road": return "Unlocked under Crandor";
			case "Dangerous Way": return "Unlocked in the Barrows underground";
			case "Dark": return "Unlocked in the Wilderness";
			case "The Dark Beast Sotetseg": return "Unlocked in Sotetseg's arena in the Theatre of Blood";
			case "Darkly Altared": return "Unlocked during the fight with Skotizo";
			case "Darkmeyer": return "Unlocked during the Sins of the Father quest";
			case "Darkness in the Depths": return "Unlocked in the Chasm of Fire";
			case "Davy Jones' Locker": return "Unlocked in the Mogre Camp";
			case "Dead Can Dance": return "Unlocked in the Wilderness. It could also be unlocked during a cutscene in the 2021 Halloween event.";
			case "Dead Quiet": return "Unlocked in the north area of Mort Myre Swamp";
			case "Deadlands": return "Unlocked in Haunted Woods just outside Port Phasmatys";
			case "Deep Down": return "Unlocked on the bottom floor of the Abandoned Mine";
			case "Deep Wildy": return "Unlocked in the Wilderness";
			case "Delrith": return "Unlocked during Demon Slayer";
			case "The Depths": return "Unlocked during the Contact! quest";
			case "Desert Heat": return "Unlocked near Nardah";
			case "Desert Voyage": return "Unlocked near the Desert Mining Camp";
			case "The Desert": return "Unlocked to the west of the Kharidian Desert";
			case "The Desolate Isle": return "Unlocked on Waterbirth Island";
			case "The Desolate Mage": return "Unlocked upon reaching Mount Quidamortem's summit";
			case "A Desolate Past": return "Unlocked in the Crypt of Tonali during The Final Dawn";
			case "Devils May Care": return "Unlocked in the Smoke Devil Dungeon.";
			case "Diango's Little Helpers": return "Unlocked in Diango's Christmas Workshop";
			case "Dies Irae": return "Unlocked during in the 2015 Halloween event";
			case "Dimension X": return "Unlocked in the Gorak Plane";
			case "Distant Land": return "Unlocked at Burgh de Rott";
			case "Distillery Hilarity": return "Unlocked during the Trouble Brewing minigame";
			case "Dogs of War": return "Unlocked in the first level of the Stronghold of Security";
			case "Dogfight": return "Unlocked during The General's Shadow";
			case "Domain of the Vampyres": return "Unlocked during the Darkness of Hallowvale quest";
			case "Don't Panic Zanik": return "Unlocked during Land of the Goblins";
			case "The Doom": return "Unlocked while fighting the Doom of Mokhaiotl";
			case "The Doors of Dinh": return "Unlocked at the Wintertodt Camp";
			case "Doorways": return "Unlocked in an area around Varrock and on the Isle of Souls.";
			case "Dorgeshuun City": return "Unlocked at Dorgesh-Kaan";
			case "Dorgeshuun Deep": return "Unlocked in the Dorgesh-Kaan South Dungeon";
			case "Dorgeshuun Treaty": return "Unlocked during The Lost Tribe";
			case "Dot's Yuletide": return "Unlocked during the 2023 Christmas event";
			case "Down and Out": return "Unlocked on Lunar Isle during the Dream Mentor quest";
			case "Down Below": return "Unlocked in the Draynor Sewers";
			case "Down by the Docks": return "Unlocked in Port Piscarilius";
			case "Down to Earth": return "Unlocked at the Earth Altar";
			case "The Dragon Slayer": return "Unlocked during the fight with Galvek during Dragon Slayer II";
			case "Dragontooth Island": return "Unlocked on Dragontooth Island";
			case "Dream": return "Unlocked in Lumbridge";
			case "Dreamstate": return "Unlocked in the Dream World of Lunar Diplomacy";
			case "The Dream Theatre": return "Unlocked during the Defender of Varrock quest";
			case "Dunes of Eternity": return "Unlocked during Beneath Cursed Sands";
			case "Dunjun": return "Unlocked in Taverley Dungeon and in the Crypt under White Knights' Castle";
			case "Dusk in Yu'biusk": return "Unlocked in Yu'biusk";
			case "Dwarf Theme": return "Unlocked near the entrance to the Dwarven Mine";
			case "Dwarven Domain": return "Unlocked in Lovakengj";
			case "Dynasty": return "Unlocked in Pollnivneach";
			case "Eagles' Peak": return "Unlocked at Eagles' Peak";
			case "Easter Jig": return "Unlocked during the 2014 Easter event";
			case "Egypt": return "Unlocked in the Kharidian Desert (unlockable in free-to-play at Shantay Pass when on Classic music mode)";
			case "Elven Guardians": return "Unlocked upon entering Prifddinas";
			case "Elven Mist": return "Unlocked at the exit of the Underground Pass";
			case "Elven Seed": return "Unlocked in Gwenith";
			case "The Emir's Arena": return "Unlocked at the Emir's Arena";
			case "Emissaries of Twilight": return "Unlocked at the Twilight Temple";
			case "Emotion": return "Unlocked at the Tree Gnome Maze";
			case "Emperor": return "Unlocked in Rimmington";
			case "The Enchanter": return "Unlocked in the Enchantment Chamber in the Mage Training Arena";
			case "The Enclave": return "Unlocked in Ferox Enclave";
			case "Escape": return "Unlocked in the Hellhound's cave south-east of Ardougne";
			case "Espionage": return "Unlocked during the Cold War quest";
			case "Etceteria": return "Unlocked on Etceteria";
			case "Eve's Epinette": return "Unlocked during the 2020 Halloween event";
			case "Everlasting": return "Unlocked in the Dream World during Dream Mentor";
			case "Everlasting Fire": return "Unlocked in the Wilderness";
			case "The Everlasting Slumber": return "Unlocked in the Sisterhood Sanctuary";
			case "The Evil Within": return "Unlocked upon Lucien's slaughter at the Chaos Temple during the While Guthix Sleeps quest";
			case "Everywhere": return "Unlocked north of Prifddinas";
			case "Evil Bob's Island": return "Unlocked on Evil Bob's island";
			case "Expanse": return "Unlocked in an area around Varrock";
			case "Expecting": return "Unlocked at the Shrine of Scorpius north of the Observatory";
			case "Expedition": return "Unlocked in the Observatory Dungeon";
			case "Exposed": return "Unlocked South of Tyras Camp";
			case "Eye See You": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Eye of the Storm": return "Unlocked during Dragon Slayer I";
			case "Faerie": return "Unlocked at Zanaris";
			case "The Fairy Dragon": return "Unlocked during Recipe for Disaster";
			case "Faith of the Hefin": return "Unlocked upon entering Prifddinas";
			case "Faithless": return "Unlocked in the Wilderness";
			case "The Fallen Empire": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Fanfare": return "Unlocked in Falador";
			case "Fanfare 2": return "Unlocked in the Karamja Ship Yard";
			case "Fanfare 3": return "Unlocked in Port Khazard";
			case "Fangs for the Memory": return "Unlocked during In Aid of the Myreque";
			case "Far Away": return "Unlocked during Mourning's End Part I";
			case "The Far Side": return "Unlocked deep within the Rogues' Den maze";
			case "A Farmer's Grind": return "Unlocked in the west wing of the Farming Guild";
			case "The Fat Lady Sings": return "Unlocked during the battle with Verzik Vitur";
			case "Fe Fi Fo Fum": return "Unlocked top of the beanstalk during Grim Tales";
			case "Fear and Loathing": return "Unlocked in Tolna's rift";
			case "The Feathered Serpent": return "Unlocked while fighting the Hueycoatl";
			case "Fenkenstrain's Refrain": return "Unlocked at Fenkenstrain's Castle";
			case "A Festive Party": return "Unlocked during the 2021 Christmas event";
			case "Fight of the Basilisk": return "Unlocked during The Fremennik Exiles";
			case "Fight or Flight": return "Unlocked in a slave mine below West Ardougne during Mourning's End Part I";
			case "Find My Way": return "Unlocked at the Ape Atoll Dungeon";
			case "Fire and Brimstone": return "Unlocked in the TzHaar Fight Pit";
			case "Fire in the Deep": return "Unlocked during the battle with the Great Olm in the Chambers of Xeric";
			case "The Fires of Lletya": return "Unlocked during Song of the Elves";
			case "Fishing": return "Unlocked at Catherby";
			case "Floating Free": return "Unlocked at Entrana during Enlightened Journey";
			case "Flute Salad": return "Unlocked in Lumbridge";
			case "Food for Thought": return "Unlocked in the Famine floor of the Stronghold of Security";
			case "Forbidden": return "Unlocked in the Wilderness";
			case "Forest": return "Unlocked north-east of Poison Waste";
			case "The Forests of Shayzien": return "Unlocked west of Shayzien";
			case "Forever": return "Unlocked in Edgeville";
			case "Forgettable Melody": return "Unlocked during Forgettable Tale...";
			case "Forgotten": return "Unlocked in Uzer";
			case "A Forgotten Religion": return "Unlocked in the Forthos Dungeon";
			case "The Forgotten Tomb": return "Unlocked during Beneath Cursed Sands";
			case "The Forlorn Homestead": return "Unlocked near the magic trees in Hosidius";
			case "The Forsaken Tower": return "Unlocked in The Forsaken Tower";
			case "The Forsaken": return "Unlocked in the Lithkren Vault";
			case "Fossilised": return "Unlocked within the Wyvern Cave on Fossil Island";
			case "The Foundry": return "Unlocked during the Sleeping Giants quest";
			case "The Fragment": return "Unlocked while fighting the Fragment of Seren during Song of the Elves";
			case "The Fremennik Kings": return "Unlocked during The Fremennik Isles quest";
			case "Frogland": return "Unlocked automatically (previously unlocked by refusing to help in the Kiss the frog random event)";
			case "Frostbite": return "Unlocked during Desert Treasure I";
			case "Fruits de Mer": return "Unlocked at the Fishing Platform";
			case "Ful to the Brim": return "Unlocked in the middle level of the Karuulm Slayer Dungeon";
			case "Funny Bunnies": return "Unlocked at any Easter event after 2013";
			case "The Galleon": return "Unlocked during the Lunar Diplomacy quest";
			case "Gaol": return "Unlocked in Gu'Tanoth";
			case "Garden": return "Unlocked in Varrock";
			case "Garden of Autumn": return "Unlocked in the Sorceress' Garden minigame";
			case "Garden of Spring": return "Unlocked in the Sorceress' Garden minigame";
			case "Garden of Summer": return "Unlocked in the Sorceress' Garden minigame";
			case "Garden of Winter": return "Unlocked in the Sorceress' Garden minigame";
			case "The Gates of Menaphos": return "Unlocked during Contact!";
			case "The Gauntlet": return "Unlocked while in The Gauntlet";
			case "The Genie": return "Unlocked in Genie's cave during the Spirits of the Elid quest";
			case "Getting Down to Business": return "Unlocked east of the Farming Guild.";
			case "Gill Bill": return "Unlocked on Molch Island";
			case "Gnome King": return "Unlocked in the Tree Gnome Stronghold";
			case "Gnome Village": return "Unlocked in the Tree Gnome Stronghold";
			case "Gnome Village 2": return "Unlocked in the Tree Gnome Stronghold";
			case "Gnome Village Party": return "Unlocked automatically";
			case "Gnomeball": return "Unlocked during the Gnome Ball minigame";
			case "Goblin Game": return "Unlocked in the Goblin Cave";
			case "Goblin Village": return "Unlocked in the Goblin Village";
			case "Golden Touch": return "Unlocked in the Alchemist Chamber in the Mage Training Arena";
			case "The Golem": return "Unlocked in the Ruins of Uzer";
			case "Greatness": return "Unlocked at an area around Varrock";
			case "Grimly Fiendish": return "Unlocked during the 2014 Halloween event";
			case "Grip of the Talon": return "Unlocked during the Shadow of the Storm quest";
			case "Grotto": return "Unlocked in the Nature Grotto";
			case "Grow Grow Grow": return "Unlocked in the north wing of the Farming Guild";
			case "Grumpy": return "Unlocked at the Feldip Hills and Corsair Cove Dungeon";
			case "The Guardian of Tapoyauik": return "Unlocked during The Heart of Darkness quest";
			case "Guardians of the Rift": return "Unlocked during the Temple of the Eye quest";
			case "The Guardians Prepare": return "Unlocked during the Temple of the Eye quest";
			case "The Guidance of Ralos": return "Unlocked on Ralos' Rise.";
			case "H.A.M. and Seek": return "Unlocked during the Another Slice of H.A.M. quest";
			case "H.A.M. Attack": return "Unlocked during the Another Slice of H.A.M. quest";
			case "H.A.M. Fisted": return "Unlocked during the Death to the Dorgeshuun quest";
			case "Harmony": return "Unlocked in the Lumbridge";
			case "Harmony 2": return "Unlocked at the Lumbridge Castle cellar";
			case "Haunted Mine": return "Unlocked in the boss fight during the Haunted Mine quest";
			case "Have a Blast": return "Unlocked during the Blast Furnace minigame";
			case "Have an Ice Day": return "Unlocked during the Cold War quest";
			case "Head to Head": return "Unlocked during Evil Twin random event";
			case "Healin' Feelin'": return "Unlocked during The Path of Glouphrie";
			case "Heart and Mind": return "Unlocked at the Body Altar";
			case "Heavy Security": return "Unlocked during The Curse of Arrav";
			case "The Heist": return "Unlocked during The Curse of Arrav";
			case "Hells Bells": return "Unlocked during the Troll Romance quest";
			case "Hermit": return "Unlocked in Saba's cave north-west of Burthorpe";
			case "High Seas": return "Unlocked in Brimhaven";
			case "High Spirits": return "Unlocked during the Halloween event in Draynor Village";
			case "His Faithful Servants": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Hoe Down": return "Unlocked upon entering the Farming Guild";
			case "Home Sweet Home": return "Unlocked inside a Player-owned house";
			case "Horizon": return "Unlocked in Taverley or during Beekeeper random event";
			case "The Houses of Kourend": return "Unlocked during the A Kingdom Divided quest";
			case "Hypnotised": return "Unlocked while hypnotised during the Icthlarin's Little Helper quest";
			case "Iban": return "Unlocked at Iban's Lair";
			case "Ice and Fire": return "Unlocked in the Wintertodt's prison";
			case "Ice Melody": return "Unlocked at White Wolf Mountain";
			case "Illusive": return "Unlocked in Dream World during Dream Mentor, also could be unlocked during the 2021 Halloween event";
			case "Impetuous": return "Unlocked in Puro-Puro";
			case "Impulses": return "Unlocked near a crop circle to Puro-Puro";
			case "In Between": return "Unlocked in Arzinian Mine";
			case "In the Brine": return "Unlocked in Mos Le'Harmless";
			case "In the Clink": return "Unlocked in the Prison Pete Random event";
			case "In the Manor": return "Unlocked south of Yanille";
			case "In the Pits": return "Unlocked in the outer area of Mor Ul Rek";
			case "In the Shadows": return "Unlocked during the Secrets of the North quest";
			case "Inadequacy": return "Unlocked during Dream Mentor";
			case "Incantation": return "Unlocked during the Shadow of the Storm quest";
			case "Incarceration": return "Unlocked during the first interrogation attempt on the shady stranger during the While Guthix Sleeps quest";
			case "Inferno": return "Unlocked in the Inferno or TzHaar-Ket-Rak's Challenges";
			case "Insect Queen": return "Unlocked in Kalphite Lair";
			case "Inspiration": return "Unlocked in the Wilderness";
			case "Into the Abyss": return "Unlocked in the Abyss";
			case "Into the Tombs": return "Unlocked in the Tombs of Amascut raid lobby";
			case "Intrepid": return "Unlocked in the Underground Pass";
			case "Invader": return "Unlocked in the Abyssal Sire's chamber within the Abyssal Nexus";
			case "Iorwerth's Lament": return "Unlocked upon entering Prifddinas";
			case "Island Life": return "Unlocked in Ape Atoll";
			case "Island of the Trolls": return "Unlocked north of Neitiznot and Jatizso";
			case "Isle of Everywhere": return "Unlocked in the East coast of Lunar Isle";
			case "Isle of Serenity": return "Unlocked on Aldarin";
			case "It's not over 'til...": return "Unlocked in Verzik Vitur's throne room";
			case "Itsy Bitsy...": return "Unlocked in the Morytania Spider Cave";
			case "Jaws of the Basilisk": return "Unlocked during The Fremennik Exiles";
			case "Jaws of Gluttony": return "Unlocked during the battle with Zebak in the Tombs of Amascut";
			case "Jester Minute": return "Unlocked during Fremennik Isles";
			case "Jolly R": return "Unlocked at the northern dock in Brimhaven";
			case "Joy of the Hunt": return "Unlocked at the Feldip Hunter area";
			case "Judgement of the Depths": return "Unlocked during the A Kingdom Divided quest";
			case "Jungle Bells": return "Unlocked during Christmas events";
			case "Jungle Hunt": return "Unlocked at the Feldip Hunter area and Myths' Guild";
			case "Jungle Island": return "Unlocked at Musa Point";
			case "Jungle Island Xmas": return "Unlocked during Christmas events";
			case "Jungle Troubles": return "Unlocked near the Jogres north of Tai Bwo Wannai";
			case "Jungly 1": return "Unlocked in Karamja";
			case "Jungly 2": return "Unlocked in Karamja";
			case "Jungly 3": return "Unlocked in Karamja";
			case "Kanon of Kahlith": return "Unlocked in the upper level of the Karuulm Slayer Dungeon";
			case "Karamja Jam": return "Unlocked in the Brimhaven Dungeon";
			case "The Kin": return "Unlocked during cutscene after the completion of While Guthix Sleeps & Dragon Slayer II";
			case "King of the Trolls": return "Unlocked during The Fremennik Isles";
			case "Kingdom": return "Unlocked at the Death Plateau";
			case "Knightly": return "Unlocked in the East Ardougne Castle";
			case "Knightmare": return "Unlocked at the Black Knights' Fortress";
			case "Kourend the Magnificent": return "Unlocked upon arrival to Port Piscarilius";
			case "La Mort": return "Unlocked at the Death Altar";
			case "Labyrinth": return "Unlocked in the Sophanem Dungeon";
			case "Lagoon": return "Unlocked underwater beneath Fossil Island";
			case "Laid to Rest": return "Unlocked in the burial chamber within the Tombs of Amascut";
			case "Lair": return "Unlocked in the Shade Catacombs";
			case "Lair of the Basilisk": return "Unlocked during The Fremennik Exiles";
			case "Lament": return "Unlocked in Enakhra's Temple";
			case "Lament for the Hallowed": return "Unlocked in Icyene Graveyard";
			case "Lament of Meiyerditch": return "Unlocked during the Darkness of Hallowvale quest";
			case "Lamistard's Labyrinth": return "Unlocked during The Curse of Arrav";
			case "Land Down Under": return "Unlocked in the caves under Miscellania";
			case "Land of Snow": return "Unlocked during the 2017 Christmas event";
			case "Land of the Dwarves": return "Unlocked in the west side of Keldagrim";
			case "Landlubber": return "Unlocked west of Brimhaven";
			case "Last King of the Yarasa": return "Unlocked during the fight with Xarpus";
			case "Last Man Standing": return "Unlocked in a Last Man Standing game";
			case "The Last Shanty": return "Unlocked in Meiyerditch";
			case "Last Stand": return "Unlocked during Swan Song quest";
			case "Lasting": return "Unlocked at Hemenster";
			case "Lava is Mine": return "Unlocked inside the Volcanic Mine on Fossil Island";
			case "Legend": return "Unlocked in Rellekka";
			case "Legion": return "Unlocked at the Barbarian Outpost";
			case "Life's a Beach!": return "Unlocked south Mos Le'Harmless";
			case "Lighthouse": return "Unlocked at the Lighthouse";
			case "Lightness": return "Unlocked north of Falador";
			case "Lightwalk": return "Unlocked at Keep Le Faye";
			case "Little Cave of Horrors": return "Unlocked at the Mos Le'Harmless Cave";
			case "Lonesome": return "Unlocked at the Desert Mining Camp";
			case "Long Ago": return "Unlocked at Hazelmere's island";
			case "Long Way Home": return "Unlocked south of Falador";
			case "The Longramble Scramble": return "Unlocked during The Path of Glouphrie";
			case "Look to the Stars": return "Unlocked during the Observatory Quest";
			case "Looking Back": return "Unlocked in the Varrock Museum";
			case "Lore and Order": return "Unlocked during King's Ransom";
			case "The Lost Melody": return "Unlocked in the Dorgesh-Kaan mine after Death to the Dorgeshuun";
			case "Lost Soul": return "Unlocked in Poison Waste";
			case "Lost to Time": return "Unlocked during the Perilous Moons quest";
			case "The Lost Tribe": return "Unlocked in the Dorgesh-Kaan mine";
			case "Lower Depths": return "Unlocked in the second sub-level of the Chambers of Xeric";
			case "Lucid Dream": return "Unlocked while in Bob's Dream World";
			case "Lucid Nightmare": return "Unlocked during the fight with Robert the Strong";
			case "Lullaby": return "Unlocked south-west of Rellekka";
			case "Lumbering": return "Unlocked during the Making Friends with My Arm quest";
			case "The Lunar Isle": return "Unlocked in Lunar Isle";
			case "Mad Eadgar": return "Unlocked in Mad Eadgar's cave";
			case "The Mad Mole": return "Unlocked at the Mole Lair";
			case "Mage Arena": return "Unlocked at the Mage Arena";
			case "Magic Dance": return "Unlocked in Yanille";
			case "Magic Magic Magic": return "Unlocked during Tower of Life";
			case "Magical Journey": return "Unlocked in Sorcerer's Tower";
			case "The Maiden's Anger": return "Unlocked during the fight with The Maiden of Sugadinti";
			case "The Maiden's Sorrow": return "Unlocked in The Maiden of Sugadinti's arena in the Theatre of Blood";
			case "Major Miner": return "Unlocked in the Jatizso mine";
			case "Making Waves": return "Unlocked at the Piscatoris Fishing Colony";
			case "Malady": return "Unlocked in the Pestilence floor of the Stronghold of Security";
			case "March": return "Unlocked at the Combat Training Camp";
			case "March of the Shayzien": return "Unlocked at the Shayziens' Wall";
			case "Marooned": return "Unlocked in Crash Island";
			case "Marzipan": return "Unlocked in Trollheim Cave";
			case "Masquerade": return "Unlocked in the Fremennik Slayer Dungeon";
			case "Master of Puppets": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Mastermindless": return "Unlocked during Recipe for Disaster quest";
			case "A Matter of Intrigue": return "Unlocked during the Twilight's Promise quest";
			case "Mausoleum": return "Unlocked at Paterdomus";
			case "Maws Jaws & Claws": return "Unlocked during the fight with Cerberus in her lair";
			case "The Maze": return "Unlocked at Melzar's Maze";
			case "Meddling Kids": return "Unlocked during Royal Trouble";
			case "Medieval": return "Unlocked in Varrock";
			case "Mellow": return "Unlocked in the Fishing Guild";
			case "Melodrama": return "Unlocked at Castle Wars";
			case "Meridian": return "Unlocked in Tirannwn";
			case "Method of Madness": return "Unlocked in Tolna's rift";
			case "Miles Away": return "Unlocked south of Falador";
			case "Military Life": return "Unlocked in the Shayzien Encampment.";
			case "The Militia": return "Unlocked in Shayzien";
			case "Mind over Matter": return "Unlocked at the Telekinetic Theatre in the Mage Training Arena";
			case "Miracle Dance": return "Unlocked at the Mind Altar";
			case "Mirage": return "Unlocked during Icthlarin's Little Helper";
			case "Miscellania": return "Unlocked in Miscellania";
			case "Mistrock": return "Unlocked in Mistrock";
			case "The Mollusc Menace": return "Unlocked during The Slug Menace";
			case "Monarch Waltz": return "Unlocked at Sinclair Mansion";
			case "Monkey Badness": return "Unlocked during Monkey Madness II";
			case "Monkey Business": return "Unlocked during Monkey Madness II";
			case "Monkey Madness": return "Unlocked in Ape Atoll";
			case "Monkey Sadness": return "Unlocked during Monkey Madness II";
			case "Monkey Trouble": return "Unlocked during Monkey Madness II";
			case "Monster Melee": return "Unlocked at the Humans Against Monsters area";
			case "The Monsters Below": return "Unlocked at Waterbirth Island";
			case "The Moons of Ruin": return "Unlocked during the Perilous Moons quest";
			case "Moody": return "Unlocked in the Underground Pass entrance area or in the Wilderness";
			case "Mor Ul Rek": return "Unlocked in the Mor Ul Rek inner city.";
			case "More Than Meets the Eye": return "Unlocked during the Secrets of the North quest";
			case "Morytania": return "Unlocked in north-west Morytania";
			case "Morytanian Mystery": return "Unlocked during the Darkness of Hallowvale quest";
			case "A Mother's Curse": return "Unlocked during the battle with Kephri in the Tombs of Amascut";
			case "Mother Ruckus": return "Unlocked during the Making Friends with My Arm quest";
			case "Mouse Trap": return "Unlocked during Grim Tales";
			case "Mudskipper Melody": return "Unlocked at Mudskipper Point";
			case "Museum Medley": return "Unlocked in the Old School Museum (alternatively, by completing the 20th Anniversary event or 2021 Birthday event)";
			case "Mutant Medley": return "Unlocked during Creature Creation minigame";
			case "My Arm's Journey": return "Unlocked during My Arm's Big Adventure";
			case "Mystics of Nature": return "Unlocked upon entering Prifddinas";
			case "Mythical": return "Unlocked in the Myths' Guild";
			case "Narnode's Theme": return "Unlocked in the Grand Tree mine";
			case "Natural": return "Unlocked near the Nature Grotto";
			case "The Navigator": return "Unlocked during The Fremennik Trials";
			case "Nether Realm": return "Unlocked in the metal dragon slayer area in Brimhaven Dungeon.";
			case "Neverland": return "Unlocked at the Tree Gnome Stronghold";
			case "Newbie Farming": return "Unlocked south of the Farming Guild";
			case "Newbie Melody": return "Unlocked at Tutorial Island";
			case "Night of the Vampyre": return "Unlocked during Darkness of Hallowvale";
			case "Nightfall": return "Unlocked south of Falador.";
			case "The Nightmare Continues": return "Unlocked during the fight with the Pestilent Bloat";
			case "No Pasaran": return "Unlocked during Song of the Elves";
			case "No Way Out": return "Unlocked at the Hopelessness Room of Tolna's rift";
			case "The Noble Rodent": return "Unlocked during Ratcatchers";
			case "Nomad": return "Unlocked in Ruins of Unkah";
			case "Norse Code": return "Unlocked in Jatizso";
			case "The North": return "Unlocked during The Curse of Arrav";
			case "Not a Moment of Relief": return "Unlocked north of Arceuus";
			case "Nox Irae": return "Unlocked during the 2015 Halloween event";
			case "Noxious Awakening": return "Unlocked while fighting Araxxor in the Morytania Spider Cave";
			case "Null and Void": return "Unlocked at the Void Knight's[sic] Outpost";
			case "Ogre the Top": return "Unlocked during The Fremennik Isles, during the fight against the Ice Troll King";
			case "Oh Rats!": return "Unlocked while fighting Scurrius in the Varrock Sewers";
			case "The Old Ones": return "Unlocked during The Garden of Death";
			case "On the Frontline": return "Unlocked on the Kebos Battlefront";
			case "On the Shore": return "Unlocked in Corsair Cove";
			case "On the Up": return "Unlocked during Dream Mentor";
			case "On the Wing": return "Unlocked in the Piscatoris Hunter area, near the Falconer";
			case "On Thin Ice": return "Unlocked during fight with Vorkath";
			case "Oncoming Foe": return "Unlocked during the Zorgoth's assault during Dragon Slayer II";
			case "Organ Music 1": return "Unlocked automatically";
			case "Organ Music 2": return "Unlocked automatically";
			case "Oriental": return "Unlocked in Ah Za Rhoon during Shilo Village";
			case "The Other Side": return "Unlocked in Port Phasmatys";
			case "Out at the Mines": return "Unlocked at the Blast mine";
			case "Out of the Deep": return "Unlocked during Horror from the Deep";
			case "Over the Mountains": return "Unlocked in the Custodia Mountains";
			case "Over to Nardah": return "Unlocked in Nardah";
			case "Overpass": return "Unlocked in Arandar, east of Tirannwn";
			case "Overture": return "Unlock in Seers' Village";
			case "Parade": return "Unlocked in Silvarea";
			case "The Part Where You Die": return "Unlocked during the A Kingdom Divided quest";
			case "Path of Peril": return "Unlocked at the Shadow Dungeon";
			case "The Penguin Bards": return "Unlocked during Cold War";
			case "Penguin Plots": return "Unlocked during Cold War";
			case "Pathways": return "Unlocked at the Brimhaven Dungeon entrance";
			case "Peace and Prosperity": return "Unlocked on Aldarin";
			case "Pest Control": return "Unlocked in the Pest Control Minigame";
			case "Pharaoh's Tomb": return "Unlocked at the Agility Pyramid";
			case "The Pharaoh": return "Unlocked during Beneath Cursed Sands";
			case "Phasmatys": return "Unlocked at the ectoplasm in the Ectofuntus.";
			case "Pheasant Peasant": return "Unlocked during the Freaky Forester random event";
			case "Pick & Shovel": return "Unlocked in the Motherlode Mine";
			case "Pinball Wizard": return "Unlocked in the Pinball Random Event";
			case "Pirates of Penance": return "Unlocked during wave 10 of Barbarian Assault";
			case "Pirates of Peril": return "Unlocked near the Pirates' Hideout in the deep Wilderness";
			case "Plots and Plans": return "Unlocked during the Children of the Sun quest";
			case "The Plundered Tomb": return "Unlocked during The Curse of Arrav";
			case "Poles Apart": return "Unlocked at the Rellekka Hunter area";
			case "The Power of Tears": return "Unlocked during the Tears of Guthix minigame";
			case "Power of the Shadow Realm": return "Unlocked during the fight with Sotetseg";
			case "Predator Xarpus": return "Unlocked in Xarpus' arena in the Theatre of Blood";
			case "Preservation": return "Unlocked upon arriving at Fossil Island";
			case "Preserved": return "Unlocked at the Fossil Island Volcano";
			case "Prime Time": return "Unlocked during Elemental Workshop II";
			case "Principality": return "Unlocked in Burthorpe";
			case "Prison Break": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Prospering Fortune": return "Unlocked in Civitas illa Fortis.";
			case "Quest": return "Unlocked at the Fire Altar";
			case "The Quizmaster": return "Unlocked in the Quiz Master Random Event";
			case "Race Against the Clock": return "Unlocked in the Camdozaal Vault";
			case "Rat a Tat Tat": return "Unlocked at the Varrock Rat Pits";
			case "Rat Hunt": return "Unlocked during Ratcatchers";
			case "Ready for Battle": return "Unlocked in the waiting room in Castle Wars";
			case "Ready for the Hunt": return "Unlocked in the Hunter Guild.";
			case "Regal": return "Unlocked in the Wilderness";
			case "Regal Pomp": return "Unlocked during the A Kingdom Divided quest";
			case "Reggae": return "Unlocked in the south-east area of the Kharazi Jungle.";
			case "Reggae 2": return "Unlocked at the eastern area of the Karamja jungle";
			case "Reign of the Basilisk": return "Unlocked during The Fremennik Exiles";
			case "Relics": return "Unlocked in the Dragonkin laboratory on Crandor during Dragon Slayer II";
			case "Rellekka": return "Unlocked in Rellekka";
			case "Rest in Peace": return "Unlocked in Death's Office";
			case "Revenants": return "Unlocked in the Revenant Caves";
			case "Rhapsody": return "Unlocked via the 'Background-music' option on the Clan Hall piano";
			case "Right on Track": return "Unlocked during Forgettable Tale...";
			case "Righteousness": return "Unlocked at the Law Altar";
			case "Rising Damp": return "Unlocked in the Brine Rat Cavern";
			case "The Rising Sun": return "Unlocked during The Heart of Darkness and The Final Dawn";
			case "Riverside": return "Unlocked west of Tyras Camp";
			case "Roc and Roll": return "Unlocked during the fight against the Giant Roc";
			case "The Rogues' Den": return "Unlocked in The Rogues' Den, located in Burthorpe";
			case "Roll the Bones": return "Unlocked in the Graveyard Chamber in the Mage Training Arena";
			case "Romancing the Crone": return "Unlocked during Troll Romance";
			case "Romper Chomper": return "Unlocked at the ogre area south of Castle Wars";
			case "Roots and Flutes": return "Unlocked while fighting Bryophyta";
			case "Rose": return "Unlocked during the A Kingdom Divided quest";
			case "Royale": return "Unlocked at the Black Knights' Base in Taverley Dungeon";
			case "Rugged Terrain": return "Unlocked at the Graveyard of Heroes in Shayzien";
			case "The Route of All Evil": return "Unlocked during the fight with Surok Magis during the While Guthix Sleeps quest";
			case "The Route of the Problem": return "Unlocked during the mercenary attack on McGrubor's Wood during the While Guthix Sleeps quest";
			case "The Ruins of Camdozaal": return "Unlocked during the Below Ice Mountain quest";
			case "Ruins of Isolation": return "Unlocked during Beneath Cursed Sands";
			case "Rune Essence": return "Unlocked in the Rune essence mine";
			case "Sad Meadow": return "Unlocked during Plague City";
			case "Safety in Numbers": return "Unlocked entering the Sourhog Cave during A Porcine of Interest";
			case "Saga": return "Unlocked south of Rellekka, near the bridge";
			case "Sands of Time": return "Unlocked during the battle with Akkha in the Tombs of Amascut";
			case "Sarachnis": return "Unlocked during the fight with Sarachnis";
			case "Sarcophagus": return "Unlocked during Desert Treasure I";
			case "Sarim's Vermin": return "Unlocked during Ratcatchers";
			case "Scape Ape": return "Unlocked automatically";
			case "Scape Cave": return "Unlocked in the cave below Tutorial Island.";
			case "Scape Crystal": return "Unlocked automatically";
			case "Scape Five": return "Unlocked automatically";
			case "Scape Ground": return "Unlocked automatically";
			case "Scape Home": return "Unlocked automatically";
			case "Scape Hunter": return "Unlocked automatically";
			case "Scape Main": return "Unlocked automatically";
			case "Scape Original": return "Unlocked automatically";
			case "Scape Sad": return "Unlocked in the Wilderness";
			case "Scape Santa": return "Unlocked automatically";
			case "Scape Scared": return "Unlocked automatically";
			case "Scape Soft": return "Unlocked north of Falador.";
			case "Scape Wild": return "Unlocked in the Wilderness.";
			case "Scar Tissue": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Scarab": return "Unlocked during Desert Treasure I";
			case "Scorching Horizon": return "Unlocked in the Avium Savannah";
			case "School's Out": return "Unlocked during the Surprise Exam random event";
			case "Scorpia Dances": return "Unlocked in the cave beneath the Scorpion Pit, where Scorpia resides";
			case "Scrubfoot's Descent": return "Unlocked during the 2020 Christmas event";
			case "Sea Minor Shanty": return "Unlocked during the 2020 Halloween event";
			case "Sea Shanty": return "Unlocked at Musa Point.";
			case "Sea Shanty 2": return "Unlocked at Port Sarim.";
			case "Sea Shanty Xmas": return "Unlocked at a Christmas event.";
			case "Secrets of the North": return "Unlocked during the Secrets of the North quest";
			case "The Seed of Crwys": return "Unlocked upon entering Prifddinas";
			case "Serenade": return "Unlocked at the Observatory";
			case "Serene": return "Unlocked at the Air Altar.";
			case "Servants of Strife": return "Unlocked in Molch";
			case "The Setting Sun": return "Unlocked during The Final Dawn";
			case "Settlement": return "Unlocked in the Mountain Camp";
			case "The Shadow": return "Unlocked on Crandor";
			case "Shadowland": return "Unlocked at east of Mort'ton";
			case "Sharp End of the Crystal": return "Unlocked in the Iorwerth Dungeon";
			case "Shattered Relics": return "Unlocked automatically";
			case "Shine": return "Unlocked around Mage Training Arena.";
			case "Shining": return "Unlocked in the Wilderness";
			case "Shining Spirit": return "Unlocked at the Corporeal Beast's cave";
			case "Shipwrecked": return "Unlocked at the shipwreck east of Fenkenstrain's Castle";
			case "Showdown": return "Unlocked during Monkey Madness I, at the ape atoll banana plantation during the fight against the Jungle Demon";
			case "Sigmund's Showdown": return "Unlocked during Death to the Dorgeshuun";
			case "Sign Here": return "Unlocked while fighting Yama in the Chasm of Fire";
			case "The Sinclairs": return "Unlocked during King's Ransom";
			case "The Slayer": return "Unlocked in the Fremennik Slayer Dungeon";
			case "The Sound of Guthix": return "Unlocked upon entering the Ancient Guthixian Temple during the While Guthix Sleeps quest";
			case "Slice of Silent Movie": return "Unlocked during Another Slice of H.A.M.";
			case "Slice of Station": return "Unlocked at the Dorgesh-Kaan–Keldagrim train system station";
			case "Slither and Thither": return "Unlocked during Royal Trouble";
			case "Slug a Bug Ball": return "Unlocked during The Slug Menace";
			case "Snowflake & My Arm": return "Unlocked during the Making Friends with My Arm quest";
			case "Sojourn": return "Unlocked in and around Troll Stronghold";
			case "Song of the Elves": return "Unlocked during Song of the Elves";
			case "Song of the Silent Choir": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Sorceress's Garden": return "Unlocked in the Sorceress's Garden";
			case "Soul Fall": return "Unlocked on the path towards the Soul Altar in Arceuus";
			case "Soul Wars": return "Unlocked upon entering the Soul Wars lobby";
			case "Soundscape": return "Unlocked at the Feldip Hills glider area";
			case "Sphinx": return "Unlocked during Icthlarin's Little Helper";
			case "Spirit": return "Unlocked in Varrock";
			case "Spirit of the Forest": return "Unlocked in the Auburn Valley";
			case "Spirits of the Elid": return "Unlocked during Spirits of the Elid";
			case "Spiritbloom": return "Unlocked in the Auburn Valley";
			case "Splendour": return "Unlocked around Heroes' Guild and Chaos Temple near Goblin Village";
			case "Spooky": return "Unlocked at Draynor Manor, during the Gravedigger random event and during the 2021 Halloween event.";
			case "Spooky 2": return "Unlocked at the entrance to the Haunted Mine and in the Isle of Souls dungeon.";
			case "Spooky Jungle": return "Unlocked to the south-west of Karamja";
			case "The Spurned Demon": return "Unlocked during the fight with Zalcano";
			case "The Spymaster": return "Unlocked during Contact!";
			case "Stalkers": return "Unlocked during Shadows of Custodia";
			case "Stagnant": return "Unlocked at The Hollows in Mort Myre Swamp";
			case "Stand Up and Be Counted": return "Unlocked during Song of the Elves";
			case "Starlight": return "Unlocked at the Asgarnia Ice Dungeon.";
			case "Start": return "Unlocked at Draynor Village.";
			case "Still Night": return "Unlocked at an area around Varrock";
			case "Stillness": return "Unlocked during In Search of the Myreque";
			case "Stones of Old": return "Unlocked in Quetzacalli Gorge";
			case "Storeroom Shuffle": return "Unlocked during The Path of Glouphrie";
			case "Storm Brew": return "Unlocked at the Killerwatt plane";
			case "Stranded": return "Unlocked during Desert Treasure I, at the Ice Path";
			case "Strange Place": return "Unlocked during A Tail of Two Cats";
			case "Strangled": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Stratosphere": return "Unlocked at the Cosmic Altar";
			case "Strength of Saradomin": return "Unlocked at the Saradominist camp in the God Wars Dungeon";
			case "Stuck in the Mire": return "Unlocked in Kebos Swamp";
			case "Subterranea": return "Unlocked in the Waterbirth Island Dungeon";
			case "Sunburn": return "Unlocked in the area north of the Ancient Pyramid";
			case "Sunny Side Up": return "Unlocked during the 2024 Easter event";
			case "Superstition": return "Unlocked during Legends' Quest";
			case "Surok's Theme": return "Unlocked during What Lies Below";
			case "Suspicious": return "Unlocked during Monkey Madness I";
			case "Tale of Keldagrim": return "Unlocked in eastern Keldagrim";
			case "The Talkasti People": return "Unlocked in Kastori";
			case "Talking Forest": return "Unlocked at McGrubor's Wood";
			case "Tarn Razorlor": return "Unlocked during Lair of Tarn Razorlor";
			case "A Taste of Hope": return "Unlocked during A Taste of Hope";
			case "Tears of Guthix": return "Unlocked during the Tears of Guthix minigame";
			case "Technology": return "Unlocked during Monkey Madness I";
			case "Teklan": return "Unlocked in Tal Teklan";
			case "Tempest": return "Unlocked during the fight with the Grotesque Guardians";
			case "Temple": return "Unlocked at the Temple of Marimbo Dungeon";
			case "Temple Desecrated": return "Unlocked during the fight with the Balance Elemental during the While Guthix Sleeps quest";
			case "Temple of Light": return "Unlocked during Mourning's End Part II";
			case "Temple of the Eye": return "Unlocked during the Temple of the Eye quest";
			case "Temple of Tribes": return "Unlocked during Land of the Goblins";
			case "Tempor of the Storm": return "Unlocked while fighting Tempoross";
			case "The Terrible Caverns": return "Unlocked during the Sins of the Father quest";
			case "The Terrible Tower": return "Unlocked at the Slayer Tower";
			case "The Terrible Tunnels": return "Unlocked during the Sins of the Father quest";
			case "Terrorbird Tussle": return "Unlocked during The Path of Glouphrie";
			case "Test of Companionship": return "Unlocked in the Path of Apmeken within the Tombs of Amascut";
			case "Test of Isolation": return "Unlocked in the Path of Scabaras within the Tombs of Amascut";
			case "Test of Resourcefulness": return "Unlocked in the Path of Crondis within the Tombs of Amascut";
			case "Test of Strength": return "Unlocked in the Path of Het within the Tombs of Amascut";
			case "That Sullen Hall": return "Unlocked in Cerberus's Lair";
			case "Theme": return "Unlocked at the Coal Trucks";
			case "A Thorn in My Side": return "Unlocked during the fight with the Hespori";
			case "Thrall of the Devourer": return "Unlocked during Beneath Cursed Sands";
			case "Thrall of the Serpent": return "Unlocked at Zul-Andra";
			case "Throne of the Demon": return "Unlocked during Shadow of the Storm";
			case "Tick Tock": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Time Out": return "Unlocked during the Maze Random Event";
			case "Time to Mine": return "Unlocked during Between a Rock...";
			case "Tiptoe": return "Unlocks in Draynor Manor cellar.";
			case "Title Fight": return "Unlocked in the Champions' Challenge area";
			case "Tomb Raider": return "Unlocked in Pyramid Plunder";
			case "Tomorrow": return "Unlocks at the coastline south of Port Sarim.";
			case "Too Many Cooks...": return "Unlocked during the goblin sub-quest in Recipe for Disaster and during 2020 Christmas Event";
			case "The Tower of Voices": return "Unlocked upon entering Prifddinas";
			case "The Tower": return "Unlocked north-west of East Ardougne";
			case "The Trade Parade": return "Unlocks at the Grand Exchange.";
			case "Trahaearn Toil": return "Unlocked upon entering Prifddinas";
			case "Trawler": return "Unlocked during the Fishing Trawler minigame";
			case "Trawler Minor": return "Unlocked during the Fishing Trawler minigame";
			case "Tree Spirits": return "Unlocked west of the Tree Gnome Stronghold";
			case "Tremble": return "Unlocked at the Death Plateau";
			case "Tribal": return "Unlocked east of Tai Bwo Wannai";
			case "Tribal 2": return "Unlocked at the gnome glider area in Karamja";
			case "Tribal Background": return "Unlocked at the south-east area of the Kharazi Jungle";
			case "Trinity": return "Unlocked at the Legends' Guild";
			case "Troll Shuffle": return "Unlocked during the Making Friends with My Arm quest";
			case "Trouble Brewing": return "Unlocked during the Trouble Brewing minigame";
			case "Troubled": return "Unlocked in the Wilderness";
			case "Troubled Waters": return "Unlocked at the Kraken Cove";
			case "Truth": return "Unlocked during The Final Dawn";
			case "Twilight": return "Unlocked during Elemental Workshop I";
			case "TzHaar!": return "Unlocked in the TzHaar Fight Cave";
			case "Undead Army": return "Unlocked during the Defender of Varrock quest";
			case "Undead Dungeon": return "Unlocked in Tarn's Lair";
			case "Under the Mountain": return "Unlocked in Cam Torum";
			case "Undercurrent": return "Unlocked in the Wilderness";
			case "Underground": return "Unlocked at Entrana Dungeon, Black demons in Taverley Dungeon, or in the Wilderness";
			case "Underground Pass": return "Unlocked during Underground Pass";
			case "Understanding": return "Unlocked at the Nature Altar";
			case "The Undying Light": return "Unlocked in Avium Savannah";
			case "Unknown Land": return "Unlocked in Draynor Village";
			case "Untouchable": return "Unlocked during Dream Mentor";
			case "Unturned Stones": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Upcoming": return "Unlocked at the Necromancer Tower";
			case "Upir Likhyi": return "Unlocked during Sins of the Father";
			case "Upper Depths": return "Unlocked upon entering the Chambers of Xeric";
			case "Vampyre Assault": return "Unlocked during the In Aid of the Myreque quest";
			case "Vanescula": return "Unlocked during A Taste of Hope";
			case "Varlamore's Sunset": return "Unlocked in Sunset Coast";
			case "The Vault": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Venomous": return "Unlocked automatically";
			case "Venture": return "Unlocked at the Digsite";
			case "Venture 2": return "Unlocked during The Dig Site";
			case "Victory is Mine": return "Unlocked while fighting a champion in the Champions' Challenge minigame";
			case "Village": return "Unlocked at Canifis";
			case "Vision": return "Unlocked at the Wizards' Tower";
			case "Volcanic Vikings": return "Unlocked in Neitiznot";
			case "Voodoo Cult": return "Unlocked during Legends' Quest";
			case "Voyage": return "Unlocked at Baxtorian Falls";
			case "The Waiting Game": return "Unlocked upon entering the Soul Wars lobby";
			case "Waking Dream": return "Unlocked during Lunar Diplomacy";
			case "Waste Defaced": return "Unlocked during The Path of Glouphrie";
			case "A Walk in the Woods": return "Unlocked in the Kourend Woodland";
			case "The Walking Dead": return "Unlocked in the Shayzien Crypts";
			case "Wally the Hero": return "Unlocked during Demon Slayer";
			case "Wander": return "Unlocks in Draynor Village";
			case "Warpath": return "Unlocked in a Clan Wars arena. (Random between this song and Clan Wars Song, re-enter to unlock both)";
			case "Warrior": return "Unlocked during The Fremennik Trials";
			case "Warriors' Guild": return "Unlocked at the Warriors' Guild";
			case "Watch Your Step": return "Unlocked in the Hallowed Sepulchre";
			case "Waterfall": return "Unlocked at the Baxtorian Falls";
			case "Waterlogged": return "Unlocked south of Canifis";
			case "Way of the Enchanter": return "Unlocked in the Lunar Isle mine";
			case "Way of the Wyrm": return "Unlocked in the lower level of the Karuulm Slayer Dungeon";
			case "Wayward": return "Unlocked in the dungeon beneath Jiggig";
			case "We are the Fairies": return "Unlocked at the Cosmic entity's plane";
			case "Welcome to my Nightmare": return "Unlocked in the Pestilent Bloat's arena in the Theatre of Blood";
			case "Welcome to the Theatre": return "Unlocked at Ver Sinhaza";
			case "Well Hallowed Air": return "Unlocked in the Hallowed Sepulchre";
			case "Well of Voyage": return "Unlocked during Regicide";
			case "What Happens Below...": return "Unlocked in the Warrens";
			case "Where Eagles Lair": return "Unlocked during Eagles' Peak";
			case "Whispering Wind": return "Unlocked in the mountains around Quetzacalli Gorge";
			case "Wild Isle": return "Unlocked in the Wilderness";
			case "Wild Side": return "Unlocked in the Wilderness";
			case "Wilderness": return "Unlocked in the Wilderness";
			case "Wilderness 2": return "Unlocked in the Wilderness";
			case "Wilderness 3": return "Unlocked in the Wilderness";
			case "Wildwood": return "Unlocked in the Wilderness";
			case "Winter Funfair": return "Unlocked during the 2017 Christmas event";
			case "Witching": return "Unlocked in the Wilderness";
			case "Woe of the Wyvern": return "Unlocked in the Asgarnian Ice Dungeon in the Skeletal Wyvern area";
			case "Wonder": return "Unlocked in the Wilderness";
			case "Wonderous": return "Unlocked near the Legends' Guild";
			case "Woodland": return "Unlocked at the Iorwerth Camp in Tirannwn";
			case "Work Work Work": return "Unlocked during the Tower of Life quest";
			case "Workshop": return "Unlocked in Falador";
			case "A Worthy Foe": return "Unlocked during Desert Treasure II - The Fallen Empire";
			case "Wrath and Ruin": return "Unlocked at the anger room in Tolna's rift";
			case "Xenophobe": return "Unlocked on the bottom level of the Waterbirth Island Dungeon";
			case "Yesteryear": return "Unlocked in Lumbridge";
			case "You Have My Attention": return "Unlocked during the Sins of the Father quest";
			case "Zamorak Zoo": return "Unlocked in God Wars Dungeon";
			case "Zanik's Theme": return "Unlocked during Land of the Goblins";
			case "Zaros Zeitgeist": return "Unlocked during the fight with Nex";
			case "Zealot": return "Unlocked at the Water Altar";
			case "Zogre Dance": return "Unlocked south of Castle Wars where you start the Zogre Flesh Eaters quest";
			case "Zombie Invasion": return "Unlocked during the Defender of Varrock quest";
			case "Zombiism": return "Unlocked on Harmony Island";
			default: return "";
		}
	}
}
